-- 코드를 입력하세요
SELECT
    B.FLAVOR
FROM FIRST_HALF A
INNER JOIN ICECREAM_INFO B ON(A.FLAVOR=B.FLAVOR)
WHERE 1=1
AND A.TOTAL_ORDER > 3000
AND B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC